# Generated by Django 5.2.6 on 2025-10-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscription_emailnotification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotification',
        ),
    ]
